packages:
  - "."
catalog:
  commander: 14.0.0
  inquirer: 12.7.0
  chalk: 5.4.1
  cli-table3: 0.6.5
  ora: 8.2.0
  yaml: 2.8.0
  fs-extra: 11.3.0
  glob: 11.0.3
  semver: 7.7.2
  npm-registry-fetch: 18.0.2
  pacote: 21.0.0
  lodash: ^4.17.21
  rxjs: 7.8.2
  zod: 3.25.75
  typescript: 5.8.3
  vitest: ^3.2.4
  eslint: 9.30.1
  "@eslint/js": ^9.30.1
  prettier: 3.6.2
catalogs:
  node18:
    "@types/node": 24.0.10
  node20:
    "@types/node": 24.0.10
