packages:
  - '.'

catalog:
  # CLI Dependencies
  commander: ^11.1.0
  inquirer: ^9.2.12
  chalk: ^5.3.0
  cli-table3: ^0.6.3
  ora: ^7.0.1
  
  # File Processing
  yaml: ^2.3.4
  fs-extra: ^11.2.0
  glob: ^10.3.10
  
  # Version Management
  semver: ^7.5.4
  npm-registry-fetch: ^16.2.1
  pacote: ^17.0.4
  libnpmconfig: ^1.2.1
  
  # Utilities
  lodash: ^4.17.21
  rxjs: ^7.8.1
  zod: ^3.22.4
  
  # Development
  typescript: ^5.3.3
  vitest: ^1.1.3
  eslint: ^8.56.0
  prettier: ^3.1.1

catalogs:
  # Different Node.js versions for testing
  node18:
    '@types/node': ^18.19.0
  
  node20:
    '@types/node': ^20.10.6